import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner/Banner";
import Navbar from "@/components/Navbar/Navbar";
import SectionCards from "@/components/Card/SectionCard";

import { getPopularVideos, getVideos } from "../lib/videoApi";



export async function getServerSideProps(){
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos('productivity');
  const travelVideos = await getVideos('Ghana music')
  const popularVideos = await getPopularVideos();
  // const popularVideos = await getVideos('pupolar'), )
  return {
    props: { disneyVideos, productivityVideos, travelVideos,popularVideos },
  };
}


export default function Home(props) {

  const { disneyVideos, productivityVideos, travelVideos, popularVideos } =
    props;
  console.log({
    disney: disneyVideos,
    product: productivityVideos,
    travel: travelVideos,
    popular: popularVideos,
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className={styles.main}>
         <Navbar username={"emmanuelfo"} />
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />

        <SectionCards
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        />
        <SectionCards title="Travel" videos={travelVideos} size="small" />

        <SectionCards title="Popular" videos={popularVideos} size="small" />
      </div>
       </div>
     
    </>
  );
}
